<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>1059a5e6-4771-4278-b48f-7ba856093ffe</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorApp\BlazorApp.csproj" />
  </ItemGroup>

</Project>
